language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - pypy3


# blacklist
branches:
  except:
    - topic/rewrite_phantomjs
    - topic/rewrite_phantomjs_2


before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then 
      sudo apt-get -qq install liblua5.2-dev;
    fi


# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then
      for i in 1 2 3; do pip install -q -r requirements.txt && break || sleep 20; done;
    else
      for i in 1 2 3; do pip install -q -r requirements-pypy.txt && break || sleep 20; done;
    fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then
      pip install -q git+https://github.com/bastibe/lunatic-python.git@f3f68d2c8638c6f423912264aeb750f5f7eb14ee#egg=lunatic-python;
    fi
  - for i in 1 2 3; do pip install -q coverage python-coveralls warcat youtube-dl && break || sleep 20; done


# command to run tests
script:
  - pip install . -t thematrix/ --no-dependencies
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then
      cd thematrix/ && nosetests --with-coverage --cover-package=wpull --cover-branches;
    else
      cd thematrix/ && nosetests;
    fi


after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then
      coveralls;
    fi
