language: python
python:
  - 3.2
  - 3.3

before_install:
  - sudo apt-get install liblua5.2-dev


# command to install dependencies
install:
  - pip install -r requirements.txt;
  - pip install git+https://github.com/bastibe/lunatic-python.git@f3f68d2c8638c6f423912264aeb750f5f7eb14ee#egg=lunatic-python


# command to run tests
script:
  - nosetests
