language: python
python:
  - 3.2
  - 3.3
  - pypy3

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then 
      sudo apt-get install liblua5.2-dev;
    fi


# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then
      pip install -r requirements.txt;
    else
      pip install -r requirements-pypy.txt;
    fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then
      pip install git+https://github.com/bastibe/lunatic-python.git@f3f68d2c8638c6f423912264aeb750f5f7eb14ee#egg=lunatic-python;
    fi
  - pip install coverage python-coveralls


# command to run tests
script:
  - pip install . -t thematrix/ --no-dependencies
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then
      cd thematrix/ && nosetests --with-coverage --cover-package=wpull --cover-branches;
    else
      cd thematrix/ && nosetests;
    fi


after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then
      coveralls;
    fi
