language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
      pip install -r requirements-py2.txt &&
      pip install unittest2 &&
      pip install hg+https://bitbucket.org/amentajo/lib3to2#egg=3to2;
    else
      pip install -r requirements.txt;
    fi


# command to run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
      python setup.py --name &&
      nosetests py2src_noedit;
    else
      nosetests;
    fi
